kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: eureka-manage
  name: eureka-manage
  namespace: default
spec:
  type: NodePort
  ports:
    - name: eureka-mannage
      port: 3001
      targetPort: 3001
      nodePort: 30002
  selector:
    k8s-app: eureka-manage
