kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: eureka-manage
  name: eureka-manage
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 3001
      nodePort: 3001
  selector:
    k8s-app: eureka-manage
