server:
  port: ${server-port}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: ${register-with-eureka}     # 是否注册到eureka
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    prefer-ip-address: false
    hostname: ${instance-hostname}


spring:
  kafka:
    bootstrap-servers: 39.100.73.134:9092     #Kafka服务端地址
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  profiles:
    active: dev
  redis:
    port: 6379
    host: 39.100.132.241
    password: 123456