server:
  port: ${server-port}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: ${register-with-eureka}     # 是否注册到eureka
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    prefer-ip-address: false
    hostname: ${instance-hostname}


spring:
  kafka:
    bootstrap-servers: 39.100.73.134:9092     #Kafka服务端地址
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  profiles:
    active: dev
  redis:
    port: 6379
    host: 39.100.132.241
    password: 123456


  ######################################################
  #   数据库连接相关配置
  ######################################################
  datasource:
    url: jdbc:mysql://39.100.132.241:3306/eureka_manage?autoReconnect=true&amp;characterEncoding=utf-8&failOverReadOnly=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
    ##映射方式配置，若配置成SpringPhysicalNamingStrategy，在进行映射时,首字母小写，大写字母变为下划线加小写
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


