server:
  port: 3001
spring:
  application:
    name: eureka-manage
  redis:
    port: 6379
    host: 39.100.132.241
    password: 123456
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${eureka_url}