server:
  port: 3001
spring:
  kafka:
    bootstrap-servers: 39.100.73.134:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  profiles:
    active: dev
  application:
    name: eureka-manage
  redis:
    port: 6379
    host: 39.100.132.241
    password: 123456
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${eureka_url}
#logging:
#  level:
#    root: debug